version: "3"

services:
    web-server:
        build: ./image_flask
        image: seed-image-flask-len-ext
        container_name: www-10.9.0.80
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.80

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

